name: Deploy to Meteora

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy with git pull
              env:
                  SERVER: "${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}"
              run: |
                  # SSH into the server and pull the latest changes
                  ssh -o StrictHostKeyChecking=no ${{ env.SERVER }} "
                  source ~/.nvm/nvm.sh &&
                  nvm use node &&
                  cd meteora-pools &&
                  git pull origin main &&
                  npm install &&
                  npm run start:prod
                  "
